version: "3.6"
services:
    etiketten:
        image: registry.simon-haas.eu/etiketten
        build:
            context: ./src
            dockerfile: ../Dockerfile
        container_name: etiketten_nginx
        restart: always
        ports:
            - 8080:80
        volumes:
            - ./src:/usr/share/nginx/html
            