version: "3.6"
services:
    etiketten:
        image: registry.simon-haas.eu/etiketten
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: etiketten_nginx
        image: nginx
        restart: always
        ports:
            - 8084:80
        volumes:
            - ./:/usr/share/nginx/html
            